from setuptools import setup, find_packages

setup(
    name="diabetes_prediction_ml_pipeline",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "pandas",
        "numpy",
        "scikit-learn",
        "matplotlib",
        "seaborn",
    ],
    entry_points={
        "console_scripts": [
            "diabetes-train=src.train:main",
            "diabetes-evaluate=src.evaluate:main",
        ],
    },
)
